### ISSUE TITLE
fix: duplicate metric name should throw error

### ISSUE THREAD

**Issue by subhankarb** [waterdipai/datachecks#106]
**Describe the bug**
In the configuration file, there is no duplication check logic for the metric name

**Expected behavior**
All the metric names must be unique.

**Screenshots**
It should throw an error if the same name for another metric
<img width="575" alt="Screenshot 2023-09-24 at 10 31 54 AM" src="https://github.com/waterdipai/datachecks/assets/2178361/6e9d95db-3b9b-4312-bcb7-55b6b30df8ec">

**Comment by dusklight00** [comment]
Hi, I'm Rahul. Me and @WeryZebra-Yue met in OSI today. I would really like to take on this issue.

**Comment by WeryZebra-Yue** [comment]
Yes, indeed @dusklight00! I've assigned you the issue; please let me know if you have any questions!

**Comment by dusklight00** [comment]
Thank you bhaiya, I'm on it!

**Comment by WeryZebra-Yue** [comment]
Hey @dusklight00, Let me know if you're stuck with anything. Feel free to ask.

**Comment by dusklight00** [comment]
Yeah definitely, I'm currently trying to understand the codebase
