### ISSUE TITLE
feat: Implement Distinct Count metrics.

### ISSUE THREAD

**Issue by PULAK0717** [waterdipai/datachecks#50]
**Tell us about the problem you're trying to solve**

As a user, I want to generate distinct count for the data column.

**Describe the solution you’d like**

A distinct count metric in data quality measures the number of unique values within a dataset, ensuring accuracy and completeness.

**Example**

Input:

| E_ID | First_Name | Last_Name | City |
|------|------------|-----------|------|
| 001  | Harry      | Gomez     | NY   |
| 002  | James      | Watson    | LA   |
| 003  | Helen      | Parker    | NY   |
| 004  | Christi    | William   | OH   |
| 005  | Ellen      | Evans     | OH   |

Output:

distinct_count = 3

Explanation: we are calculating the distinct count of cities in the "City" column. The expected output is 3 because there are three unique cities in the dataset: New York(NY), Los Angeles(LA), and Ohio(OH).

**Comment by subhankarb** [comment]
Resolved by #67
